# Generated by Django 6.1 on 2026-08-28 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['household', 'in_progress'], name='events_even_househo_657f1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('in_progress', False), ('ended_at__isnull', True), _connector='OR'), name='in_progress_events_have_no_end'),
        ),
    ]
