# Generated by Django 6.1 on 2026-08-29 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('accepted_by__isnull', True)), models.Q(('accepted_at__isnull', False), ('accepted_by__isnull', False)), _connector='OR'), name='invite_acceptance_is_all_or_nothing'),
        ),
    ]
