# Generated by Django 6.1 on 2026-08-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_invite_email_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='feed_interval_min',
            field=models.PositiveIntegerField(default=180),
        ),
    ]
